"""Grounding Verification and Zero-Hallucination Evaluator.

Implements SDD Section 2 (NFR-3.1), Section 4.2.2, and Section 6.3 to guarantee
that policy answers maintain high groundedness with 0% tolerated hallucination.
"""
import logging
import re
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class GroundingResult:
    """Evaluation result for factual grounding of an answer against retrieved context."""

    is_grounded: bool
    score: float
    citations_found: list[str] = field(default_factory=list)
    details: str = ""


class GroundingEvaluator:
    """Self-reflective grounding and factual entailment evaluator."""

    def __init__(self, threshold: float = 0.65):
        self.threshold = threshold

    def evaluate(self, response: str, evidence: list[dict[str, Any]]) -> GroundingResult:
        """Evaluate whether response is grounded in retrieved context chunks.

        Args:
            response: Final answer generated by the agent.
            evidence: List of tool return payloads captured during reasoning.
        """
        if not response or not response.strip():
            return GroundingResult(is_grounded=True, score=1.0, details="Empty response")

        # Extract all textual content retrieved by tools
        context_corpus = []
        citations = []
        for item in evidence:
            payload = item.get("payload") if isinstance(item, dict) else None
            if not payload:
                continue

            # OKF tool returns: {"content": ..., "title": ..., "resource": ...}
            if isinstance(payload, dict):
                content = payload.get("content") or payload.get("grounded_context") or ""
                if content:
                    context_corpus.append(str(content))
                title = payload.get("title")
                resource = payload.get("resource")
                if resource:
                    citations.append(str(resource))
                elif title:
                    citations.append(str(title))
                for cit in payload.get("citations", []):
                    citations.append(str(cit))

        # If no retrieval tools were called (e.g., direct greetings or conversational turns)
        if not context_corpus:
            return GroundingResult(
                is_grounded=True,
                score=1.0,
                citations_found=[],
                details="No retrieval context required for this turn",
            )

        combined_context = " ".join(context_corpus).lower()
        response_lower = response.lower()

        # Token overlap / keyword n-gram entailment estimate
        # Filter out common stop words to evaluate factual keyword alignment
        stop_words = {
            "the", "a", "an", "in", "on", "at", "to", "for", "of", "and", "or",
            "is", "are", "was", "were", "you", "your", "my", "our", "it", "this",
            "that", "with", "as", "be", "by", "from", "have", "has", "do", "does"
        }
        resp_tokens = [
            w for w in re.findall(r"\b[a-z]{3,}\b", response_lower)
            if w not in stop_words
        ]

        if not resp_tokens:
            return GroundingResult(is_grounded=True, score=1.0, citations_found=citations)

        matched_tokens = sum(1 for t in resp_tokens if t in combined_context)
        score = matched_tokens / len(resp_tokens)

        is_grounded = score >= self.threshold
        if not is_grounded:
            logger.warning(
                "GroundingEvaluator: Potential policy hallucination detected. Score=%.2f (threshold=%.2f)",
                score,
                self.threshold,
            )

        return GroundingResult(
            is_grounded=is_grounded,
            score=round(score, 3),
            citations_found=citations,
            details=f"Token entailment overlap: {matched_tokens}/{len(resp_tokens)} keywords grounded",
        )
